// ==UserScript==
// @name         Arena 模型助手 · Assets 整合版
// @namespace    arena-model-companion.local
// @version      2026.09.26.8
// @description  页面主环境模型探针、抽卡、通知及会话显示；会话模型跨域同步需另装助手脚本
// @match        https://arena.ai/*
// @match        https://10minutemail.one/*
// @run-at       document-start
// @grant        none
// @sandbox      raw
// @noframes
// ==/UserScript==

// Generated by tools/build-userscript.cjs. Asset provenance: __BUILD_PROVENANCE__
(function(){
'use strict';
if(window.top!==window||!['arena.ai','10minutemail.one'].includes(location.hostname))return;
if(window.__ARENA_USERSCRIPT__)return;
const api=window.__ARENA_USERSCRIPT__={version:'2026.09.26.8',loaded:[],errors:[]};
function load(name,fn){try{const result=fn();api.loaded.push(name);return result;}catch(e){api.errors.push({name,message:String(e.message||e)});console.warn('[Arena userscript]',name,e);}}
load('AuthBridge.js',()=>{
__BUILD_AUTH__
});
if(location.hostname==='arena.ai'){
__BUILD_ACCOUNTS__(api);
load("PageBridge.js",()=>{
__BUILD_PAGE__
});
load("CandidateBridge.js",()=>{
__BUILD_CANDIDATE__
});
load("ConversationRecovery.js",()=>{
__BUILD_RECOVERY__
});
load("FollowLatest.js",()=>{
__BUILD_FOLLOW__
});
api.markdown=load('ConversationMarkdown.js',()=>(__BUILD_MARKDOWN__));
api.balance=load('ArenaBalance.js',()=>(__BUILD_BALANCE__));
if(api.accounts)api.balance=()=>api.accounts.balanceSnapshot();
load('arena-model-probe.inject.js',()=>{
__BUILD_PROBE__
});
load('userscript-thinking-stop.js',()=>__BUILD_THOUGHTSTOP__(api));
load('userscript-reasoning.js',()=>__BUILD_REASONING__(api));
load('userscript-session-models.js',()=>__BUILD_MODELS__(api));
__BUILD_USAGE__(api);
load('userscript-task-review-hider.js',()=>__BUILD_REVIEW__(api));
load('userscript-composer-visibility.js',()=>__BUILD_COMPOSER__(api));
load('userscript-composer-auto-esc.js',()=>__BUILD_COMPOSERESC__(api));
}
__BUILD_ADAPTER__(api,__BUILD_RESOURCES__);
})();
