const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../assets/arena-model-probe.inject.js'),'utf8');
function load(){const c=vm.createContext({performance,console,TextDecoder,TextEncoder,atob,btoa,AbortController,URL,setTimeout,clearTimeout,location:{origin:'https://arena.ai',pathname:'/agent/11111111-1111-1111-1111-111111111111'}});vm.runInContext(source.replace('try { __req("main"); }','try { globalThis.req=__req; }'),c);return c.req;}
function span(n,level='high',extra={}){return {spanId:String(n).repeat(16),kind:'stream',turn:1,partial:false,traceOrder:n,values:{requestModel:'model-'+n},reasoning:level?[{kind:'effort',level,path:'$.ai.settings.reasoningEffort'}]:[],...extra};}
function facts(rows,detail={}){const req=load(),s=req('trace-summary'),summary=s.latestTraceSummary({spans:rows,...detail});return {req,summary,value:s.desktopFacts(null,[],[{source:'reasoning.config',config:{kind:'effort',level:'max'}}],summary)};}
test('latest ordered call determines effort, without mixing previous call or request',()=>{const {summary,value}=facts([span(1,'high'),span(2,'low')]);assert.equal(summary.coverage,'ambiguous');assert.equal(summary.usage,null);assert.equal(summary.internalModel,null);assert.equal(value.effort.level,'low');assert.equal(value.latestCall.requestModel,'model-2');assert.equal(value.latestCall.spanId,'2'.repeat(16));assert.equal(value.effort.evidence[0].path,'$.ai.settings.reasoningEffort');});
test('nanosecond start times override array and Trace order without rounding',()=>{const {value}=facts([span(2,'low',{startTimeNs:'1720000000000000002'}),span(3,'high',{startTimeNs:'1720000000000000001'})]);assert.equal(value.effort.level,'low');assert.equal(value.latestCall.order,'start-time');});
test('equal latest timestamps are ambiguous even if Trace order differs',()=>{const {value}=facts([span(1,'high',{startTimeNs:'1720000000000000001'}),span(2,'low',{startTimeNs:'1720000000000000001'})]);assert.equal(value.latestCall,null);assert.equal(value.effort.status,'unknown');});
test('missing or duplicate order cannot guess the last array element',()=>{for(const order of [null,1]){const {value}=facts([span(1),span(2,'low',{traceOrder:order})]);assert.equal(value.latestCall,null);assert.equal(value.effort.status,'unknown');}});
test('latest missing effort never falls back to older high',()=>{const {value}=facts([span(1),span(2,null)]);assert.equal(value.latestCall.spanId,'2'.repeat(16));assert.equal(value.effort.status,'unknown');});
test('latest unfinished call never falls back to a finished call',()=>{const {value}=facts([span(1),span(2,'low',{partial:true})]);assert.equal(value.latestCall.partial,true);assert.equal(value.effort.status,'unknown');});
test('limited or stopped collection cannot assert the latest call',()=>{for(const detail of [{limited:true},{stopped:'429'}]){const {value}=facts([span(1),span(2,'low')],detail);assert.equal(value.latestCall,null);assert.equal(value.effort.status,'unknown');}});
test('newest turn only and latest-call conflict stay distinct from previous calls',()=>{let r=facts([span(1,'high',{turn:1}),span(2,'low',{turn:2}),span(3,'medium',{turn:2})]);assert.equal(r.value.effort.level,'medium');const c=span(2);c.reasoning.push({kind:'effort',level:'low'});r=facts([span(1,'medium'),c]);assert.equal(r.value.effort.status,'conflict');assert.ok(!r.value.effort.display.includes('medium'));});
test('trace metadata survives event selection parsing and sanitization',()=>{const req=load(),a=req('agent-detail'),runId='run_test',message='ai.streamText.doStream';const events=[{runId,message:'chat turn 1'},...[1,2].map(n=>({runId,message,spanId:String(n).repeat(16),isPartial:false,startTime:'172000000000000000'+n}))];const selected=a.selectDetailSpans({events},runId).selected;const spans=selected.map((event,i)=>a.parseDetailSpan({...events[i+1],properties:{'ai.settings.reasoningEffort':i?'low':'high','ai.model.id':'demo-'+i}},event,runId));const clean=a.sanitizeDetail({spans});assert.equal(clean.spans[1].traceOrder,2);assert.equal(clean.spans[1].startTimeNs,'1720000000000000002');assert.equal(req('trace-summary').latestTraceSummary(clean).latestCall.effort.level,'low');});
test('latest-call HUD uses the selected model name and escapes it, never the older label',()=>{const {req,value}=facts([span(1),span(2,'low',{values:{requestModel:'<latest>'}})]);const mock={root:{querySelectorAll:()=>[],innerHTML:''},logs:[],confidenceClass:()=>''};req('ui').HUD.prototype.render.call(mock,{mode:'RESOLVED',modelId:'old',label:'old',confidence:1,evidence:[]},{reasoningFacts:value,reasoning:value.effort,realModel:{name:'old',all:['old','other']}});assert.ok(mock.root.innerHTML.includes('&lt;latest&gt; · low'));assert.ok(mock.root.innerHTML.includes('最新调用'));assert.ok(!mock.root.innerHTML.includes('old · low'));assert.ok(!mock.root.innerHTML.includes('<latest>'));});
