const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'tools/userscript-reasoning.js'),'utf8');
const probeContext=vm.createContext({performance});
vm.runInContext(fs.readFileSync(path.join(root,'assets/arena-model-probe.inject.js'),'utf8').replace('try { __req("main"); }','try { globalThis.req=__req; }'),probeContext);
const resolveModelName=probeContext.req('reasoning').resolveModelName;
const url='https://arena.ai/agent/11111111-1111-1111-1111-111111111111';
const sid=n=>String(n).repeat(16);
const call=(id=1,level='high',turn=1)=>({spanId:sid(id),kind:'stream',turn,partial:false,values:{requestModel:'demo'},reasoning:level?[{kind:'effort',level,path:'$.ai.settings.reasoningEffort'}]:[]});
const detail=(spans=[call()])=>({checkedAt:'2026-09-26T00:00:00Z',spans});
function load(){let account='account-a',reload=false;const api={accounts:{scope:()=>account,requiresReload:()=>reload}};const run={runId:'run_one',tokenUrl:url,minTurn:0,lastSeenTurn:1,automaticTrace:{url,runId:'run_one',generation:3,detail:detail()}};
 const window={__MODEL_PROBE__:{conversationModels:()=>({[url.split('/').at(-1)]:'demo'}),resolveModelName,runState:()=>run,bus:{activeRunId:'run_one',generation:3,evidence:[]}}};const context={window,location:{origin:'https://arena.ai',pathname:new URL(url).pathname},setInterval:()=>1};vm.runInNewContext(source,context)(api);
 return {api:api.reasoningInspector,run,window,context,account:v=>{account=v;},reload:v=>{reload=v;}};}
const plain=x=>JSON.parse(JSON.stringify(x));
test('all seven explicit levels survive, budget and mode are separate',()=>{const {api}=load();for(const level of ['none','minimal','low','medium','high','xhigh','max'])assert.equal(api.analyze(detail([call(1,level)])).calls[0].effort.value,level);
 const c=call(1,null);c.reasoning=[{kind:'budget',value:8192},{kind:'mode',value:'adaptive'}];const e=api.analyze(detail([c])).calls[0].effort;assert.equal(e.status,'unknown');assert.deepEqual(plain(e.budgets),[8192]);assert.deepEqual(plain(e.modes),['adaptive']);});
test('conflict and unsupported values never become guessed effort',()=>{const {api}=load(),c=call();c.reasoning.push({kind:'effort',level:'low'});assert.equal(api.analyze(detail([c])).calls[0].effort.status,'conflict');c.reasoning=[{kind:'effort',level:'private-unknown'}];const r=api.analyze(detail([c]));assert.equal(r.calls[0].effort.status,'unsupported');assert.ok(!JSON.stringify(r).includes('private-unknown'));});
test('unknown and large token count do not become high',()=>{const {api}=load(),c=call(1,null);c.values.reasoningTokens=99999;const r=api.analyze(detail([c])).calls[0];assert.equal(r.effort.value,null);assert.equal(r.reasoning.value,99999);});
test('zero usage distinct from missing and conflicts',()=>{const {api}=load();assert.equal(api.reported([]).status,'missing');assert.equal(api.reported([{value:0}]).status,'zero');assert.equal(api.reported([{value:1},{value:2}]).status,'conflict');});
test('model suffix is independent; model name itself is not a tier',()=>{const {api}=load();assert.equal(api.hint('demo-high-vertex','demo').value,'high');assert.equal(api.hint('qwen-max','qwen-max').value,null);assert.equal(api.hint('other-high','demo').status,'基座不一致，待核对');});
test('multiple calls retain independent levels and do not inherit turn records',()=>{const {api}=load();const r=api.analyze(detail([call(1,'high'),call(2,'low'),{spanId:sid(3),kind:'usage',turn:1,partial:false,values:{modelName:'demo-max',reasoningTokens:8000}}]),[{kind:'effort',level:'medium'}]);assert.equal(r.calls.length,2);assert.equal(r.calls[0].effort.value,'high');assert.equal(r.calls[1].effort.value,'low');for(const c of r.calls){assert.equal(c.reasoning.value,null);assert.equal(c.internalModel,null);assert.equal(c.recordCorrelation,'not-attributed');}});
test('single call combines matching config sources with provenance, reporting conflict',()=>{const {api}=load();const c=api.analyze(detail(),[{kind:'effort',level:'low',path:'$.reasoning_effort'}]).calls[0];assert.equal(c.effort.status,'conflict');assert.deepEqual(plain(c.effort.evidence.map(e=>e.source)),['Span','页面请求']);assert.equal(c.effort.evidence[0].path,'$.ai.settings.reasoningEffort');});
test('single-call usage record and Google metadata may agree or conflict',()=>{const {api}=load(),c=call();c.providerMeta={'google.usageMetadata.thoughtsTokenCount':4};const u={spanId:sid(2),kind:'usage',turn:1,partial:false,values:{reasoningTokens:4,modelName:'demo-high'}};let r=api.analyze(detail([c,u])).calls[0];assert.equal(r.reasoning.value,4);assert.equal(r.internalHint.value,'high');u.values.reasoningTokens=5;r=api.analyze(detail([c,u])).calls[0];assert.equal(r.reasoning.status,'conflict');});
test('latest turn only, duplicate spans ignored, partial flags retained',()=>{const {api}=load(),c=call(2,'low',2);c.partial=true;const r=api.analyze(detail([call(),c,c]));assert.equal(r.turn,2);assert.equal(r.calls.length,1);assert.equal(r.partial,true);});
test('private text and malicious paths never enter inspector snapshot',()=>{const {api}=load(),c=call();c.prompt='PRIVATE';c.values.password='PRIVATE';c.reasoning=[{kind:'effort',level:'high',path:'$.password.PRIVATE'},{kind:'mode',value:'PRIVATE'}];const r=api.analyze(detail([c]));assert.ok(!JSON.stringify(r).includes('PRIVATE'));});
test('snapshot requires confirmed account, session, active run and generation',()=>{for(const change of [e=>e.account(null),e=>e.reload(true),e=>e.run.tokenUrl=url+'x',e=>e.run.automaticTrace.generation=2,e=>e.window.__MODEL_PROBE__.bus.activeRunId='other',e=>e.run.automaticTrace.url=url+'x',e=>e.run.minTurn=1,e=>e.run.lastSeenTurn=2]){const e=load();change(e);assert.notEqual(e.api.snapshot().state,'ready');}});
test('same run is never reassigned to another account',()=>{const e=load();assert.equal(e.api.snapshot().state,'ready');e.account('account-b');assert.equal(e.api.snapshot().state,'blocked');});
test('new route or turn clears old display facts',()=>{const e=load();assert.equal(e.api.snapshot().calls.length,1);e.context.location.pathname='/agent/22222222-2222-2222-2222-222222222222';assert.equal(e.api.snapshot().calls.length,0);});
test('page request evidence requires current page and generation',()=>{const e=load();const bus=e.window.__MODEL_PROBE__.bus;bus.evidence=[{source:'reasoning.config',config:{kind:'effort',level:'low',source:'request'},pageUrl:url,generation:2}];assert.equal(e.api.snapshot().calls[0].effort.value,'high');bus.evidence[0].generation=3;assert.equal(e.api.snapshot().calls[0].effort.status,'conflict');});
test('read-only module introduces no network hooks, persistent state or unsafe HTML',()=>{assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|localStorage|sessionStorage|innerHTML|GM_|\.click\s*\(|location\.reload/);});
test('manifest and static module entry include inspector',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(root,'userscript-build/manifest.json'),'utf8'));assert.equal(manifest.reasoningInspector,crypto.createHash('sha256').update(source).digest('hex'));const candidate=fs.readFileSync(path.join(root,'userscript-build/user.candidate.js'),'utf8');assert.ok(candidate.includes(source.trim()));assert.ok(candidate.includes('思考等级检查'));assert.ok(candidate.includes('data-reasoning-inspector'));});

test('mounted UI is idempotent, escapes model text, preserves evidence expansion and clears stale data',()=>{
 class Element{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.isConnected=true;this.textContent='';}append(x){this.children.push(x);}replaceChildren(){this.children=[];}setAttribute(){}querySelectorAll(){return all(this).filter(x=>x.tag==='details'&&x.open);}}
 const all=x=>[x,...x.children.flatMap(all)],e=load();e.context.document={createElement:t=>new Element(t)};let intervals=0;e.context.setInterval=()=>{intervals++;return 1;};
 const malicious='<img src=x onerror=alert(1)>',parent=new Element('root');e.run.automaticTrace.detail.spans[0].values.requestModel=malicious;
 e.api.mount(parent);e.api.mount(parent);assert.equal(parent.children.length,1);assert.equal(intervals,1);assert.equal(all(parent).filter(n=>n.tag==='img').length,0);assert.ok(all(parent).some(n=>n.textContent===malicious+' · high'));
 const d=all(parent).find(n=>n.tag==='details');d.open=true;e.run.automaticTrace.detail.spans[0].values.reasoningTokens=0;e.api.refresh();assert.equal(all(parent).find(n=>n.tag==='details').open,true);assert.ok(all(parent).some(n=>n.textContent.includes('推理 Token：0')));
 e.window.__MODEL_PROBE__.bus.generation++;e.api.refresh();assert.ok(!all(parent).some(n=>n.textContent===malicious+' · high'));assert.equal(all(parent).filter(n=>n.tag==='details').length,0);
});
test('duplicate turn-level usage records are not assigned to the single model call',()=>{const {api}=load(),usage=id=>({spanId:sid(id),kind:'usage',turn:1,partial:false,values:{reasoningTokens:5}});const r=api.analyze(detail([call(),usage(2),usage(3)])).calls[0];assert.equal(r.reasoning.value,null);assert.equal(r.recordCorrelation,'not-attributed');});

test('compatibility upload helper uses probe fallback or internal-probe, never effort decoration',()=>{const e=load();assert.equal(e.api.uploadModel().model,'demo');e.run.automaticTrace.detail.spans.push({spanId:sid(2),kind:'usage',turn:1,partial:false,values:{modelName:'internal-high'}});let result=e.api.uploadModel();assert.equal(result.model,'internal-high-demo');assert.equal(result.source,'reasoning-inspector');assert.equal(result.sessionId,'11111111-1111-1111-1111-111111111111');assert.ok(!result.model.includes(' · '));e.run.automaticTrace.detail.spans[0].partial=true;assert.equal(e.api.uploadModel(),null);});
test('ambiguous internal names, multiple calls and stale scopes never upload',()=>{for(const change of [e=>e.run.automaticTrace.detail.spans.push(call(3,'low')),e=>e.run.automaticTrace.detail.spans.push({spanId:sid(3),kind:'cost',turn:1,partial:false,values:{modelName:'different'}}),e=>e.account(null),e=>e.window.__MODEL_PROBE__.bus.generation++]){const e=load();e.run.automaticTrace.detail.spans.push({spanId:sid(2),kind:'usage',turn:1,partial:false,values:{modelName:'internal-high'}});change(e);assert.equal(e.api.uploadModel(),null);}});
test('HUD remount moves the same inspection DOM with expanded sources preserved',()=>{
 class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.dataset={};this.isConnected=true;this.textContent='';}append(node){if(node.parent)node.parent.children=node.parent.children.filter(x=>x!==node);this.children.push(node);node.parent=this;}replaceChildren(){this.children=[];}setAttribute(){}querySelectorAll(){return all(this).filter(x=>x.tag==='details'&&x.open);}}
 const all=x=>[x,...x.children.flatMap(all)],e=load();const first=new Element('slot'),second=new Element('slot');let slot=first;e.context.document={createElement:t=>new Element(t),getElementById:()=>({shadowRoot:{querySelector:()=>slot}})};
 e.api.mountHud();const section=first.children[0],details=all(first).find(x=>x.tag==='details');details.open=true;slot=second;e.api.mountHud();assert.equal(first.children.length,0);assert.equal(second.children[0],section);assert.equal(all(second).find(x=>x.tag==='details'),details);assert.equal(details.open,true);
});
