const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),src=fs.readFileSync(path.join(root,'tools/userscript-account-compat.js'),'utf8');
function setup(options={}){
 const storage=options.storage||new Map(),events={},clicks={},requests=[],timers=[];let stops=0,resets=0,id='account-a';const api={};
 const w={__AMP_PAGE_GACHA__:{stop(){stops++;}},__MODEL_PROBE__:{reset(){resets++;},usdQuotaSnapshot:()=>options.usd?.()},addEventListener:(n,f)=>events[n]=f};
 const document={body:null,hidden:false,addEventListener:(n,f)=>clicks[n]=f,getElementById:()=>null};
 const fetch=async(p,o)=>{requests.push([p,o]);if(options.fetch)return options.fetch(p,o,requests.length);if(p==='/api/me')return {ok:true,json:async()=>({user:id?{id,isAnonymous:false}:null})};if(p==='/api/billing/balance')return {ok:!options.billingFail,status:503,json:async()=>({creditsRemaining:options.zero?0:123,dailyFreeCredits:500,secret:'never store'})};return {ok:true,json:async()=>({pulse:options.zero?0:45,secret:'never store'})};};
 w.fetch=fetch;const c=vm.createContext({window:w,document,location:{hostname:'arena.ai'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},Date,AbortController,setTimeout:(f,ms)=>{timers.push([f,ms]);return timers.length;},clearTimeout(){},setInterval(){}});
 vm.runInContext(src,c)(api);return {api,storage,events,clicks,requests,w,stops:()=>stops,resets:()=>resets,setId:v=>id=v};
}
test('initially unverified; legacy unscoped gacha snapshots are not resumed',()=>{const storage=new Map([['amp_page_gacha_session','old']]);const e=setup({storage});assert.equal(e.api.accounts.canOperate(),false);assert.equal(e.api.accounts.scope(),null);assert.equal(storage.has('amp_page_gacha_session'),false);assert.equal(e.requests.length,0);});
test('fresh identity is checked before and after quotas; only allowlisted cache fields published',async()=>{const e=setup();await e.api.accounts.refresh();assert.equal(e.api.accounts.canOperate(),true);assert.equal(e.api.accounts.scope(),'account-a');assert.equal(e.requests.filter(x=>x[0]==='/api/me').length,2);assert.deepEqual(JSON.parse(e.storage.get('amp.lite.v2.balance')),{remaining:123,daily:500,at:e.api.accounts.status().checkedAt});assert.equal(JSON.parse(e.storage.get('amp.lite.v2.pulse')).pulse,45);assert.ok(![...e.storage.values()].join('').includes('secret'));for(const [url,o]of e.requests){assert.ok(url.startsWith('/api/'));assert.equal(o.method,'GET');assert.equal(o.credentials,'same-origin');}});
test('zero balance and pulse are retained, not treated as missing',async()=>{const e=setup({zero:true});await e.api.accounts.refresh();assert.equal(e.api.accounts.balanceSnapshot().creditsRemaining,0);assert.equal(JSON.parse(e.storage.get('amp.lite.v2.pulse')).pulse,0);});
test('failed balance fetch is unavailable, not fabricated from cached data',async()=>{const e=setup({billingFail:true,storage:new Map([['amp.lite.v2.balance','{"remaining":999}']])});await e.api.accounts.refresh();assert.equal(e.api.accounts.balanceSnapshot().status,'unavailable');assert.equal(e.storage.has('amp.lite.v2.balance'),false);assert.equal(e.api.accounts.canOperate(),true);});
test('account event stops automation but leaves forced scrolling unchanged',async()=>{const e=setup();await e.api.accounts.refresh();const epoch=e.api.accounts.epoch();let suspensions=0,idleOff=0;e.w.__arenaFollowLatest={suspend(){suspensions++;return {ok:true};},setEnabled(v){assert.equal(v,false);idleOff++;}};e.events['amp:account']({detail:'do-not-trust-this-as-identity'});assert.equal(e.api.accounts.canOperate(),false);assert.equal(e.api.accounts.requiresReload(),true);assert.ok(e.api.accounts.epoch()>epoch);assert.equal(e.stops(),1);assert.equal(suspensions,0);assert.equal(idleOff,0);assert.equal(e.resets(),1);const n=e.requests.length;await e.api.accounts.refresh();assert.equal(e.requests.length,n);assert.equal(e.storage.has('amp.lite.v2.balance'),false);});
test('failed account check does not toggle or suspend forced scrolling',async()=>{const e=setup({fetch:async()=>({ok:false,status:401})});let idleOff=0,suspensions=0;e.w.__arenaFollowLatest={setEnabled(v){assert.equal(v,false);idleOff++;},suspend(){suspensions++;}};await e.api.accounts.refresh();assert.equal(e.api.accounts.canOperate(),false);assert.equal(idleOff,0);assert.equal(suspensions,0);});
test('same-tab dirty marker detected synchronously before automation',async()=>{const e=setup();await e.api.accounts.refresh();e.storage.set('amp.account.dirty','changed');assert.equal(e.api.accounts.canOperate(),false);assert.equal(e.api.accounts.requiresReload(),true);});
test('existing dirty marker at startup is acknowledged without reload loop',async()=>{const e=setup({storage:new Map([['amp.account.dirty','previous']])});await e.api.accounts.refresh();assert.equal(e.api.accounts.canOperate(),true);assert.equal(e.api.accounts.requiresReload(),false);});
test('switcher click freezes first, preserving old mirrors for companion mirrorOut',async()=>{const e=setup();await e.api.accounts.refresh();e.clicks.click({target:{closest:()=>true}});assert.equal(e.api.accounts.canOperate(),false);assert.equal(e.storage.has('amp.lite.v2.balance'),true);e.events['amp:account']({});assert.equal(e.storage.has('amp.lite.v2.balance'),false);});
test('identity changed between requests never publishes mixed-account results',async()=>{let me=0;const e=setup({fetch:async p=>({ok:true,json:async()=>p==='/api/me'?{user:{id:++me===1?'a':'b'}}:p.includes('balance')?{creditsRemaining:999}:{pulse:99}})});await e.api.accounts.refresh();assert.equal(e.api.accounts.requiresReload(),true);assert.equal(e.storage.has('amp.lite.v2.balance'),false);});
test('late response after account event cannot repopulate cleared mirrors',async()=>{let resolve;const gate=new Promise(r=>resolve=r);const e=setup({fetch:async p=>{if(p.includes('balance'))await gate;return {ok:true,json:async()=>p==='/api/me'?{user:{id:'a'}}:p.includes('balance')?{creditsRemaining:999}:{pulse:99}};}});const task=e.api.accounts.refresh();await Promise.resolve();await Promise.resolve();e.events['amp:account']({});resolve();await task;assert.equal(e.api.accounts.canOperate(),false);assert.equal(e.storage.has('amp.lite.v2.balance'),false);});
test('anonymous session remains blocked',async()=>{const e=setup();e.setId(null);await e.api.accounts.refresh();assert.equal(e.api.accounts.scope(),null);assert.equal(e.api.accounts.canOperate(),false);});
test('USD mirror uses fresh genuine quota snapshots, never credits conversion',async()=>{let usd={status:'ready',checkedAt:new Date().toISOString(),quota:{balanceRemainingUsd:0.42,allowanceUsd:2,overLimit:false,private:'drop'}};const e=setup({usd:()=>usd});await e.api.accounts.refresh();usd.checkedAt=new Date().toISOString();e.api.accounts.publishUsd();const value=JSON.parse(e.storage.get('amp.lite.v2.usd'));assert.equal(value.balanceRemainingUsd,.42);assert.equal(value.allowanceUsd,2);assert.equal(value.private,undefined);e.events['amp:account']({});e.api.accounts.publishUsd();assert.equal(e.storage.has('amp.lite.v2.usd'),false);});
test('generated balance exception only permits same-origin Arena; other blockers remain',()=>{const code=fs.readFileSync(path.join(root,'userscript-build/user.candidate.js'),'utf8');const a=code.indexOf('function isBalancePath(url) {'),b=code.indexOf('\nfunction checkBlock',a);const c=vm.createContext({window:{__ARENA_USERSCRIPT__:{accounts:{allowBalance:true}}},URL,location:{href:'https://arena.ai/agent',origin:'https://arena.ai'}});vm.runInContext(code.slice(a,b),c);assert.equal(c.isBalancePath('/api/billing/balance'),false);assert.equal(c.isBalancePath('https://other.test/api/billing/balance'),true);assert.match(code,/Datadog RUM/);assert.match(code,/if\(window\.__ARENA_USERSCRIPT__\?\.accounts\)return false/);});
test('compatibility never uses cookie/password APIs or replaces Account Switch',()=>{assert.doesNotMatch(src,/document\.cookie|GM_cookie|GM_getValue|GM_setValue|sign-in\/email/);const built=fs.readFileSync(path.join(root,'userscript-build/user.candidate.js'),'utf8');assert.match(built,/@grant\s+none/);assert.doesNotMatch(built,/@grant\s+GM_cookie/);assert.match(built,/@version\s+2026\.09\.26\.6/);});

test('keyboard confirmation freezes before companion changes cookies',async()=>{const e=setup();await e.api.accounts.refresh();e.clicks.keydown({key:'Enter',target:{closest:()=>true}});assert.equal(e.api.accounts.requiresReload(),true);assert.equal(e.api.accounts.canOperate(),false);});
test('failed identity verification removes stale account mirrors',async()=>{const storage=new Map([['amp.lite.v2.balance','{"remaining":999}'],['amp.lite.v2.usd','{"balanceRemainingUsd":999}']]);const e=setup({storage,fetch:async()=>({ok:false,status:401})});await e.api.accounts.refresh();assert.equal(e.api.accounts.canOperate(),false);assert.equal(storage.has('amp.lite.v2.balance'),false);assert.equal(storage.has('amp.lite.v2.usd'),false);});
test('failed account verification never changes the independent scroll switch',async()=>{const e=setup({fetch:async()=>{throw Error('offline');}});let changes=0;e.w.__arenaFollowLatest={setEnabled(){changes++;},suspend(){changes++;}};await e.api.accounts.refresh();assert.equal(changes,0);assert.equal(e.api.accounts.canOperate(),false);});
