const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../tools/userscript-hit-rename.js'),'utf8');
const url='https://arena.ai/agent/11111111-1111-1111-1111-111111111111';
function setup(storage=new Map(),option={}){
 const api={accounts:option.accounts},actions=[],loc={origin:'https://arena.ai',pathname:new URL(url).pathname};let title='',dialog=false,menu=false,value='';
 const candidate=(a,v)=>{actions.push([a,v]);if(a==='ensureSidebar')option.onEnsure?.();if(a==='state')return {title,renameDialog:dialog,renameMenu:menu,renameSaveReady:dialog};if(a===option.fail)return {error:'injected failure'};if(a==='ensureSidebar'&&option.navigate)loc.pathname='/agent/22222222-2222-2222-2222-222222222222';if(a==='renameMenuClick')menu=true;if(a==='button'){menu=false;dialog=true;}if(a==='renameFill')value=v;if(a==='renameSave'){title=value;dialog=false;}return {ok:true};};
 const context=vm.createContext({window:{__arenaCandidate:candidate},location:loc,navigator:{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{if(option.storageFail)throw Error('storage denied');storage.set(k,v);}},setTimeout:fn=>queueMicrotask(fn),console:{warn(){}}});
 vm.runInContext(source,context)(api);return {api,actions,storage,loc,title:()=>title};
}
for(const kind of ['primary','secondary'])test(kind+' hit renames current conversation',async()=>{const e=setup();assert.equal(e.api.hitRename.consider({kind,model:'Model X',url}),true);await e.api.hitRename.settled();assert.equal(e.title(),'Model X 1');assert.equal(e.api.hitRename.status().state,'done');assert.equal(e.api.hitRename.busy(),false);});
test('duplicate polls and reloads do not rename or increment again',async()=>{const e=setup(),hit={kind:'primary',model:'Model X',url};e.api.hitRename.consider(hit);assert.equal(e.api.hitRename.consider(hit),true);await e.api.hitRename.settled();assert.equal(e.api.hitRename.consider(hit),false);assert.equal(e.actions.filter(a=>a[0]==='renameSave').length,1);const f=setup(e.storage);f.api.hitRename.consider(hit);await f.api.hitRename.settled();assert.equal(f.actions.length,0);assert.equal(f.api.hitRename.status().state,'already-done');});
test('sequence persists per model, across conversations',async()=>{const e=setup();e.api.hitRename.consider({kind:'secondary',model:'Model X',url});await e.api.hitRename.settled();const f=setup(e.storage);f.loc.pathname='/agent/22222222-2222-2222-2222-222222222222';f.api.hitRename.consider({kind:'secondary',model:'Model X',url:f.loc.origin+f.loc.pathname});await f.api.hitRename.settled();assert.equal(f.title(),'Model X 2');const g=setup(e.storage);g.api.hitRename.consider({kind:'primary',model:'Model Y',url});await g.api.hitRename.settled();assert.equal(g.title(),'Model Y 1');});
test('route change during rename cannot save on new conversation',async()=>{const e=setup(new Map(),{navigate:true});e.api.hitRename.consider({kind:'primary',model:'Model X',url});await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'failed');assert.equal(e.actions.some(a=>a[0]==='renameSave'),false);});
test('non-target or stale URL is ignored',()=>{const e=setup();assert.equal(e.api.hitRename.consider({kind:'other',model:'Model X',url}),false);assert.equal(e.api.hitRename.consider({kind:'primary',model:'Model X',url:url+'x'}),false);assert.equal(e.actions.length,0);});
test('storage failure prevents UI changes and releases runner lock',async()=>{const e=setup(new Map(),{storageFail:true});e.api.hitRename.consider({kind:'primary',model:'Model X',url});await e.api.hitRename.settled();assert.equal(e.api.hitRename.busy(),false);assert.equal(e.api.hitRename.status().state,'failed');assert.equal(e.actions.length,0);});
test('UI failure is reported and not retried every poll',async()=>{const e=setup(new Map(),{fail:'renameFill'}),hit={kind:'secondary',model:'Model X',url};e.api.hitRename.consider(hit);await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'failed');assert.equal(e.api.hitRename.consider(hit),false);assert.equal(e.actions.some(a=>a[0]==='renameSave'),false);});
test('candidate hook pauses runner before existing-dialog handling',()=>{const built=fs.readFileSync(path.join(__dirname,'../userscript-build/user.candidate.js'),'utf8');assert.ok(built.indexOf('if(renamer?.busy())')<built.indexOf('const hasDialog = !!(v.hasDialog'));assert.match(built,/s\.phase==='resume' && v\.conversation/);assert.match(built,/target\(f\.model\)\|\|secondary\(f\.model\)/);assert.match(built,/@version\s+2026\.09\.24\.8/);});

for(const model of ['astra-opus','gemini-2.5-pro'])test('generated runner integrates rename hold for '+model,()=>{
 const full=fs.readFileSync(path.join(__dirname,'../userscript-build/user.candidate.js'),'utf8');const start=full.indexOf('/* arena-model-probe');const main=full.indexOf('try { __req("main"); }',start);const end=full.indexOf('})();',main)+5;const probe=full.slice(start,end);
 let busy=false,time=0;const hits=[];const seen=new Set();const w={__ARENA_USERSCRIPT__:{hitRename:{busy:()=>busy,status:()=>({...hits[hits.length-1],state:busy?'running':'done'}),consider:h=>{if(seen.has(h.model))return false;seen.add(h.model);hits.push(h);busy=true;return true;}}}};
 const c=vm.createContext({window:w,performance});vm.runInContext(probe.replace('try { __req("main"); }','try { globalThis.req=__req; }'),c);
 const v={url:'https://arena.ai/agent',main:true,conversation:false,draft:'',generating:false,editor:true,sendReady:true,newLinks:1,attachmentNames:[],blocker:'',promptConfirmed:false};const f={generation:2,model:'',modelUrl:''};const calls=[];
 const bridge={read:()=>({...v}),typeDraft:(a,b)=>{v.draft=b.trim();return {ok:true};},action:n=>{calls.push(n);if(n==='send'){v.generating=true;v.conversation=true;v.url=url;v.promptConfirmed=true;v.draft='';f.generation++;f.modelUrl=url;}return {ok:true};}};
 const runner=c.req('gacha-runner').create({bridge:()=>bridge,info:()=>({...f}),now:()=>time,random:()=>.5,blocked:()=>false,claim:()=>true,release(){}});const step=(ms=250)=>{time+=ms;runner.tick();};runner.start('hello');for(let i=0;i<200&&runner.state().phase!=='answer';i++)step();assert.equal(runner.state().phase,'answer');step(500);f.model=model;step();assert.equal(hits.length,1);assert.equal(hits[0].kind,model==='astra-opus'?'primary':'secondary');v.hasDialog=true;for(let i=0;i<8;i++)step(5000);assert.equal(runner.state().status,'running');assert.equal(calls.filter(n=>n==='new').length,0);busy=false;v.hasDialog=false;step();assert.equal(hits.length,1);if(model==='astra-opus')assert.equal(runner.state().status,'matched');else {v.generating=false;v.responseComplete=true;step();assert.equal(runner.state().status,'running');assert.equal(runner.state().phase,'prepare');assert.match(runner.state().message,/已完成命名/);}
});

test('same model numbering is independent for each verified account',async()=>{const store=new Map();const accounts=name=>({scope:()=>name,canOperate:()=>true,epoch:()=>0});const hit={kind:'primary',model:'Model X',url};const a=setup(store,{accounts:accounts('user-a')});a.api.hitRename.consider(hit);await a.api.hitRename.settled();const b=setup(store,{accounts:accounts('user-b')});b.api.hitRename.consider(hit);await b.api.hitRename.settled();assert.equal(a.title(),'Model X 1');assert.equal(b.title(),'Model X 1');assert.ok(store.has('arena-userscript-hit-names-v1:user-a'));assert.ok(store.has('arena-userscript-hit-names-v1:user-b'));assert.equal(store.has('arena-userscript-hit-names-v1'),false);});
test('account switch on unchanged URL cancels pending rename',async()=>{let epoch=0,ready=true;const accounts={scope:()=> 'user-a',canOperate:()=>ready,epoch:()=>epoch};const e=setup(new Map(),{accounts,onEnsure:()=>{epoch++;ready=false;}});e.api.hitRename.consider({kind:'secondary',model:'Model X',url});await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'failed');assert.equal(e.actions.some(a=>a[0]==='renameSave'),false);});
test('unknown account cannot begin a rename or consume a number',()=>{const e=setup(new Map(),{accounts:{canOperate:()=>false}});assert.equal(e.api.hitRename.consider({kind:'primary',model:'Model X',url}),false);assert.equal(e.storage.size,0);assert.equal(e.actions.length,0);});
