const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');const source=fs.readFileSync(path.join(root,'userscript-build/user.candidate.js'),'utf8');
function sandbox(host='arena.ai',frame=false){const events=[],calls=[];const w={addEventListener(){}};w.top=frame?{}:w;
 const c=vm.createContext({window:w,location:{hostname:host,origin:'https://'+host,pathname:'/agent',href:'https://'+host+'/agent'},document:{body:null,documentElement:{},addEventListener:(...a)=>events.push(a),getElementById:()=>null},console,MutationObserver:class{observe(){}disconnect(){}},setInterval:()=>1,clearInterval(){},setTimeout,clearTimeout,URL,Blob,AbortController,performance,TextDecoder,TextEncoder,atob,btoa,fetch:async(...a)=>{calls.push(a);return {ok:true};}}, {codeGeneration:{strings:false,wasm:false}});
 // Test registration and notifier independently; no live page/network hooks are installed in this VM.
 const run=()=>vm.runInContext(source.replace('try { __req("main"); }','try { window.__testReq=__req; }'),c);
 return {w,c,events,calls,run};}
test('generated metadata selects intended hosts, page context and document-start',()=>{new vm.Script(source);assert.match(source,/@run-at\s+document-start/);assert.match(source,/@grant\s+none/);assert.match(source,/@sandbox\s+raw/);assert.match(source,/@noframes/);assert.doesNotMatch(source,/@require|@connect\s+\*/);});
test('all eight modules register without external code execution',()=>{const e=sandbox();e.run();const a=e.w.__ARENA_USERSCRIPT__;assert.equal(a.errors.length,0);assert.equal(a.loaded.length,8);assert.equal(typeof a.markdown.capture,'function');assert.equal(typeof a.balance,'function');assert.equal(typeof e.w.__arenaCompanion.action,'function');assert.equal(typeof e.w.__arenaCandidate,'function');assert.equal(typeof e.w.__arenaAuth.act,'function');assert.equal(typeof e.w.__arenaConversationRecovery.prepare,'function');assert.equal(typeof e.w.__arenaFollowLatest.setEnabled,'function');assert.equal(e.calls.length,0);});
test('repeated injection does not re-register modules or DOM listeners',()=>{const e=sandbox();e.run();const a=e.w.__ARENA_USERSCRIPT__,n=e.events.length;e.run();assert.equal(e.w.__ARENA_USERSCRIPT__,a);assert.equal(e.events.length,n);});
test('foreign hosts and frames remain untouched',()=>{for(const e of [sandbox('example.com'),sandbox('arena.ai',true)]){e.run();assert.equal(e.w.__ARENA_USERSCRIPT__,undefined);assert.equal(e.events.length,0);}});
test('mailbox host loads auth only; no probe, recovery or billing interception',()=>{const e=sandbox('10minutemail.one');e.run();assert.deepEqual(Array.from(e.w.__ARENA_USERSCRIPT__.loaded),['AuthBridge.js']);assert.equal(e.w.__MODEL_PROBE__,undefined);assert.equal(e.w.__arenaCompanion,undefined);});
test('billing adapter is unavailable before account verification',()=>{const e=sandbox();e.run();assert.equal(e.w.__ARENA_USERSCRIPT__.balance('start','id').status,'unavailable');assert.equal(e.calls.length,0);});
test('external broadcasts require explicit opt-in, and can be disabled again',async()=>{const e=sandbox();e.run();const n=e.w.__testReq('notifier');assert.equal(await n.broadcastHit('example-model',1),false);assert.equal(e.calls.length,0);e.w.__ARENA_USERSCRIPT__.broadcastEnabled=true;await n.broadcastHit('example-model',1);assert.equal(e.calls.length,1);assert.equal(e.calls[0][0],'https://meamoe.top/koa/notify2');assert.equal(e.calls[0][1].credentials,'omit');e.w.__ARENA_USERSCRIPT__.broadcastEnabled=false;await n.broadcastHit('example-model',2);assert.equal(e.calls.length,1);});
test('Markdown renderer stays callable as an expression result',()=>{const e=sandbox();e.run();const m=e.w.__ARENA_USERSCRIPT__.markdown;const result=m.render({title:'Test',url:'https://arena.ai/agent/test',capturedAt:'2026-09-24',source:'test',warnings:[],messages:m.normalize([{role:'assistant',parts:[{type:'text',text:'hello'}]}])});assert.match(result.markdown,/hello/);assert.equal(result.filename,'Test.md');});
test('provenance verifies original assets and generated output',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'userscript-build/manifest.json')));const hash=b=>crypto.createHash('sha256').update(b).digest('hex');for(const [f,h]of Object.entries(m.assets))assert.equal(hash(fs.readFileSync(path.join(root,'assets',f))),h);assert.equal(hash(source),m.outputSha256);});

function adapterHarness(host='arena.ai'){
 const elements=[],downloads=[],events=[],calls=[];
 class Element{constructor(tag){this.tagName=tag;this.children=[];this.style={};this.textContent='';this.value='';elements.push(this);}append(...v){this.children.push(...v);}setAttribute(k,v){this[k]=v;}attachShadow(){this.shadowRoot=new Element('shadow');return this.shadowRoot;}remove(){this.removed=true;}click(){if(this.tagName==='a')downloads.push({name:this.download,href:this.href});return this.onclick?.();}replaceChildren(){this.children=[];}showModal(){this.open=true;}}
 const body=new Element('body');const document={body,createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),getElementById:id=>elements.find(e=>e.id===id),addEventListener(){}};
 const w={__arenaFollowLatest:{enabled:false,setEnabled:on=>calls.push(['follow',on])},__arenaAuth:{read:()=>({stage:'loggedOut'}),act:()=>calls.push('auth')},__arenaConversationRecovery:{prepare:()=>({eligible:true,token:'t',backup:{messages:[]}}),apply:()=>{calls.push('repair');return {applied:true};}},addEventListener:(...v)=>events.push(v)};
 const api={loaded:[],errors:[],broadcastEnabled:false,markdown:{capture:()=>({}),render:()=>({filename:'test.md',markdown:'hello',stats:{},warnings:[]})}};
 const c=vm.createContext({window:w,document,location:{hostname:host,origin:'https://'+host,pathname:'/agent/test'},Blob,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},setTimeout(){},setInterval(){},confirm:()=>false,console});
 const f=vm.runInContext(fs.readFileSync(path.join(root,'tools/userscript-adapter.js'),'utf8'),c);f(api,{});
 return {elements,downloads,calls,api,w,f,button:name=>elements.find(e=>e.tagName==='button'&&e.textContent===name)};
}
test('adapter mounts once, starts collapsed, and does not perform page actions',()=>{const e=adapterHarness();assert.equal(e.elements.find(x=>x.tagName==='section').hidden,true);assert.equal(e.calls.length,0);const n=e.elements.length;e.f(e.api,{});assert.equal(e.elements.length,n);e.button('Arena 工具').click();assert.equal(e.elements.find(x=>x.tagName==='section').hidden,false);});
test('export and repair UI require explicit clicks; cancelled confirmation prevents mutation',async()=>{const e=adapterHarness();await e.button('导出 Markdown').click();assert.equal(e.downloads[0].name,'test.md');const apply=e.button('2. 确认备份后应用修复');assert.equal(apply.disabled,true);await e.button('1. 检查修复并备份').click();assert.equal(e.downloads[1].name,'arena-recovery-backup.json');assert.equal(apply.disabled,false);await apply.click();assert.equal(e.calls.includes('repair'),false);});
test('mailbox adapter omits Arena-only operations',()=>{const e=adapterHarness('10minutemail.one');assert.equal(e.button('导出 Markdown'),undefined);assert.ok(e.button('打开确认邮件'));assert.equal(e.calls.length,0);});
