const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),rename=fs.readFileSync(path.join(root,'tools/userscript-hit-rename.js'),'utf8'),candidate=fs.readFileSync(path.join(root,'assets/CandidateBridge.js'),'utf8');
const url='https://arena.ai/agent/11111111-1111-1111-1111-111111111111';
function fixture(options={}){
 let menu=false,dialog=false,sidebar=!options.lateSidebar,clicks=0,pointers=0,waits=0;const store=new Map();
 const node=(text)=>({textContent:text,getAttribute:()=>null,getClientRects:()=>[{}]});
 const item={...node('Rename'),click(){menu=false;dialog=true;}};
 const more={...node('More options'),click(){clicks++;if(options.clickMenu)menu=!menu;},dispatchEvent(e){if(e.type==='pointerdown'){pointers++;menu=!menu;}}};
 const parent={querySelectorAll:q=>q==='button'?[more]:[]};const link={...node('Old title'),href:url,parentElement:parent,scrollIntoView(){}};
 class Input{set value(v){this.v=v;}get value(){return this.v;}getClientRects(){return [{}];}dispatchEvent(){}constructor(){this.type='text';}}
 const input=new Input(),save={...node('Rename'),click(){link.textContent=input.value;dialog=false;}};
 const dlg={...node(''),innerText:'Rename chat',querySelectorAll:q=>q==='input'?[input]:q==='button'?[save]:[]};
 const expand={...node('Expand sidebar'),click(){}};
 const doc={querySelectorAll(q){if(q==='a[href]')return sidebar?[link]:[];if(q==='button')return sidebar?[more]:[expand];if(q==='[role=menuitem]')return menu?[item]:[];if(q==='[role=dialog]')return dialog?[dlg]:[];return [];}};
 let ready=true,epoch=0;const api={accounts:{canOperate:()=>ready,scope:()=>ready?'account-a':null,epoch:()=>epoch}},window={},loc={origin:'https://arena.ai',pathname:new URL(url).pathname};
 const c=vm.createContext({window,document:doc,location:loc,URL,getComputedStyle:()=>({visibility:'visible'}),Event:class{},HTMLInputElement:Input,PointerEvent:class{constructor(type,props){this.type=type;Object.assign(this,props);}},navigator:{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},setTimeout:fn=>{waits++;if(options.lateSidebar&&!options.neverReady&&waits>=3)sidebar=true;if(options.switchAtWait===waits){ready=false;epoch++;}queueMicrotask(fn);},console:{warn(){}}});
 vm.runInContext(candidate,c);vm.runInContext(rename,c)(api);
 return {api,window,store,loc,ready:()=>sidebar=true,switchAccount:()=>{epoch++;ready=false;},clicks:()=>clicks,pointers:()=>pointers,title:()=>link.textContent,hit:{kind:'primary',model:'astra-opus',url}};
}
test('candidate build includes inspected implementation and original bridge',()=>{const built=fs.readFileSync(path.join(root,'userscript-build/user.candidate.js'),'utf8');assert.ok(built.includes(rename.trim()));assert.ok(built.includes(candidate.trim()));});
test('pointerdown-only menu completes automatic naming using one fallback',async()=>{const e=fixture();e.api.hitRename.consider(e.hit);await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'done');assert.equal(e.title(),'astra-opus 1');assert.equal(e.clicks(),1);assert.equal(e.pointers(),1);});
test('click menu opens without fallback toggling it closed',async()=>{const e=fixture({clickMenu:true});e.api.hitRename.consider(e.hit);await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'done');assert.equal(e.clicks(),1);assert.equal(e.pointers(),0);});
test('sidebar rendered after more than 250ms still completes naming',async()=>{const e=fixture({lateSidebar:true});e.api.hitRename.consider(e.hit);await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'done');assert.equal(e.title(),'astra-opus 1');assert.equal(e.clicks(),1);});
test('permanent lookup failure is bounded, staged and not automatically retried',async()=>{const e=fixture({lateSidebar:true,neverReady:true});e.api.hitRename.consider(e.hit);await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'failed');assert.equal(e.api.hitRename.status().stage,'sidebar');assert.match(e.api.hitRename.status().error,/等待侧栏菜单就绪超时/);assert.equal(e.api.hitRename.consider(e.hit),false);assert.equal(e.clicks(),0);});
test('explicit retry uses pending number and succeeds, done cannot retry',async()=>{const e=fixture({lateSidebar:true,neverReady:true});e.api.hitRename.consider(e.hit);await e.api.hitRename.settled();e.ready();assert.equal(e.api.hitRename.retry(),true);await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'done');assert.equal(e.title(),'astra-opus 1');assert.equal(e.api.hitRename.retry(),false);const state=JSON.parse([...e.store.values()][0]);assert.equal(Object.values(state.counters)[0],1);});
for(const changed of ['route','account'])test(changed+' change rejects explicit retry',async()=>{const e=fixture({lateSidebar:true,neverReady:true});e.api.hitRename.consider(e.hit);await e.api.hitRename.settled();e.ready();if(changed==='route')e.loc.pathname='/agent/22222222-2222-2222-2222-222222222222';else e.switchAccount();assert.equal(e.api.hitRename.retry(),false);assert.equal(e.clicks(),0);});
test('account switch during menu wait cancels before pointer fallback',async()=>{const e=fixture({switchAtWait:1});e.api.hitRename.consider(e.hit);await e.api.hitRename.settled();assert.equal(e.api.hitRename.status().state,'failed');assert.equal(e.pointers(),0);assert.equal(e.title(),'Old title');});
test('manual retry while task active does not start another execution',async()=>{const e=fixture();e.api.hitRename.consider(e.hit);assert.equal(e.api.hitRename.retry(),false);await e.api.hitRename.settled();assert.equal(e.clicks(),1);});
