const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const{fixture,cookie,bundle,clone,webcrypto}=require('./account-vault-fixture.cjs');
const bundlePath=fs.existsSync(path.join(__dirname,'../Arena-Account-Switch.user.js'))?path.join(__dirname,'../Arena-Account-Switch.user.js'):path.join(__dirname,'Arena-Account-Switch.user.js');
const source=fs.readFileSync(bundlePath,'utf8');
function env(options={}) {
 const server=fixture(),trace=[],gmWrites=[],gmDeleted=[],gm=new Map(),ls=new Map(),session=new Map(),timers=[],notices=[];
 let jar=clone(options.cookies===undefined?[cookie('current@example.com')]:options.cookies), failSet=options.failSet||null;
 const answers=[...(options.confirm||[])];
 const storage=map=>({getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)});
 function node(){return {dataset:{},style:{setProperty(){},removeProperty(){}},classList:{add(){},remove(){},contains(){return false},toggle(){}},append(){},appendChild(){},remove(){this.isConnected=false},querySelector(){return null},querySelectorAll(){return []},addEventListener(){},focus(){},setAttribute(){},getAttribute(){return null},isConnected:true,textContent:'',innerText:''};}
 const document={documentElement:{dataset:{},classList:{contains(){return false}}},head:node(),body:node(),cookie:'',visibilityState:'visible',createElement:node,querySelector(){return null},querySelectorAll(){return []},addEventListener(){}};
 const ctx={document,location:{host:'arena.ai',pathname:'/agent',reload(){}},navigator:{platform:'Linux',userAgent:'Test',locks:{request:async(n,o,fn)=>fn(options.lockBusy?null:{})}},crypto:webcrypto,URL,URLSearchParams,TextEncoder,console:{info(){}},setTimeout:(fn,ms)=>{timers.push({fn,ms});return timers.length},clearTimeout(){},setInterval:(fn,ms)=>{timers.push({fn,ms});return timers.length},clearInterval(){},requestAnimationFrame:fn=>fn(),addEventListener(){},removeEventListener(){},dispatchEvent(){},CustomEvent:class{},KeyboardEvent:class{},getComputedStyle:()=>({fontWeight:400}),confirm:()=>answers.shift()??true,prompt:()=>null,atob:s=>Buffer.from(s,'base64').toString('binary'),escape,decodeURIComponent,encodeURIComponent,
  GM_info:{scriptHandler:'Tampermonkey',version:'5.4'},GM_getValue:(k,d)=>gm.has(k)?clone(gm.get(k)):d,GM_setValue:(k,v)=>{gm.set(k,clone(v));gmWrites.push([k,clone(v)]);},GM_deleteValue:k=>{gmDeleted.push(k);gm.delete(k);},GM_addValueChangeListener(){},GM_registerMenuCommand(){},GM_setClipboard(){},
  GM_cookie:{list:(d,cb)=>{trace.push('cookie.list');cb(clone(jar));},delete:(d,cb)=>{trace.push('cookie.delete');jar=jar.filter(c=>c.name!==d.name);cb();},set:(d,cb)=>{trace.push('cookie.set');if(failSet&&failSet(d)){failSet=null;cb('failure');return;}jar=jar.filter(c=>c.name!==d.name);if(!d.expirationDate||d.expirationDate>Date.now()/1000){const copy=clone(d);delete copy.url;copy.domain||='arena.ai';jar.push(copy);}cb();}},
  GM_xmlhttpRequest:opts=>{trace.push('http '+opts.method+' '+new URL(opts.url).pathname);const req={url:opts.url,method:opts.method,body:opts.data,headers:opts.headers};
   const action=options.intercept?.(req,server);Promise.resolve(action??server.send(req)).then(r=>opts.onload({status:r.status,responseText:JSON.stringify(r.body),responseHeaders:Object.entries(r.headers||{}).map(([k,v])=>k+': '+v).join('\r\n'),finalUrl:r.finalUrl||opts.url}),()=>opts.onerror());},
  fetch:async(url,opts)=>{trace.push('arena '+new URL(url).pathname);
   if(url.includes('/nextjs-api/sign-in/email')){const b=JSON.parse(opts.body);jar=[cookie(b.email,'fresh-login')];return{ok:options.loginOk!==false,status:options.loginOk===false?401:200,json:async()=>({success:options.loginOk!==false})};}
   if(url.includes('/api/me/pulse'))return{ok:true,json:async()=>({pulse:50})};
   if(url.includes('/api/billing/balance'))return{ok:true,json:async()=>({creditsRemaining:0,dailyFreeCredits:10})};
   if(options.verify==='network')throw new Error('network');
   if(options.verify==='invalid')return{ok:false,status:401,json:async()=>({})};
   let user=null;try{user=JSON.parse(Buffer.from(jar[0].value.slice(7),'base64url')).user;}catch{}
   return{ok:true,status:200,json:async()=>({user})};
  }
 };
 ctx.localStorage=storage(ls);ctx.sessionStorage=storage(session);ctx.window=ctx;ctx.unsafeWindow=ctx;
 const instrument=source.slice(0,source.indexOf('  // ---------------- 启动 / 元数据同步 ----------------'))+`
  toast = message => globalThis.__notices.push(message);
  openLoginForm = () => {};
  navigateAfterSwitch = () => { globalThis.__navigated = true; };
  globalThis.__api={vault,reflect,toUI,syncCurrent,switchTo0,switchTo,signInEmail,replaceAuth,setCookie,migrateLegacy,quotaToServer,quotaFromServer,legacyQuota,gmTransport,
    getAccounts:()=>accounts, getCurrent:()=>currentId};
})();`;
 ctx.__notices=notices;vm.createContext(ctx);vm.runInContext(instrument,ctx);
 async function connect(){await ctx.__api.vault.connect('https://meamoe.top/koa/arena-vault/connect#key='+server.key);ctx.__api.reflect();}
 function remote(email='target@example.com',token='target-session'){const a=server.add(email);const rec=server.records.get(a.id);rec.hasCredentials=true;rec.credentialRevision=1;server.credentials.set(a.id,bundle([cookie(email,token)]));return a;}
 return {ctx,api:ctx.__api,server,trace,gm,gmWrites,gmDeleted,timers,notices,connect,remote,get jar(){return clone(jar)}};
}
const status=(n,code)=>({status:n,body:{code:n,data:{errorCode:code}}});
test('switch fetches remote credentials before deleting current Cookie, then uploads verified session',async()=>{const e=env(),a=e.remote();await e.connect();await e.api.switchTo0(e.api.toUI(e.server.records.get(a.id)));assert.ok(e.trace.findIndex(x=>x.includes('/credentials/read'))<e.trace.indexOf('cookie.delete'));assert.equal(e.ctx.__navigated,true);assert.equal(e.server.records.get(a.id).credentialRevision,2);assert.ok(e.gmWrites.every(([k])=>['arena.vault.connection.v1','carry.v1'].includes(k)));assert.equal(e.api.getAccounts()[0].cookies,undefined);});
test('credential read outage leaves browser Cookie untouched',async()=>{const e=env({intercept:r=>r.url.endsWith('/credentials/read')?status(503,'VAULT_UNAVAILABLE'):null}),a=e.remote(),before=e.jar;await e.connect();await assert.rejects(e.api.switchTo0(e.api.toUI(a)));assert.deepEqual(e.jar,before);assert.equal(e.trace.includes('cookie.delete'),false);});
test('hostile server Cookie domain is rejected before any Cookie mutation',async()=>{const e=env(),a=e.remote(),before=e.jar;e.server.credentials.get(a.id).cookies[0].domain='evil.invalid';await e.connect();await assert.rejects(e.api.switchTo0(e.api.toUI(a)));assert.deepEqual(e.jar,before);assert.equal(e.trace.includes('cookie.delete'),false);});
test('Cookie write failure rolls back original current login',async()=>{const target=cookie('target@example.com','target-session');const e=env({failSet:d=>d.value===target.value}),a=e.remote(),before=e.jar;await e.connect();await assert.rejects(e.api.switchTo0(e.api.toUI(a)));assert.equal(e.jar[0].value,before[0].value);assert.notEqual(e.ctx.__navigated,true);});
test('Arena confirms invalid target: rollback and remote reauth flag',async()=>{const e=env({verify:'invalid'}),a=e.remote(),before=e.jar;await e.connect();assert.equal(await e.api.switchTo0(e.api.toUI(a)),false);assert.equal(e.jar[0].value,before[0].value);assert.equal(e.server.records.get(a.id).status,'reauth_required');});
test('uncertain Arena verification rolls back without marking password invalid',async()=>{const e=env({verify:'network'}),a=e.remote(),before=e.jar;await e.connect();await assert.rejects(e.api.switchTo0(e.api.toUI(a)));assert.equal(e.jar[0].value,before[0].value);assert.equal(e.server.records.get(a.id).status,'ready');});
test('vault write failure after Arena verification restores original browser session',async()=>{const e=env({intercept:r=>r.method==='PUT'&&r.url.endsWith('/credentials')&&JSON.parse(Buffer.from(JSON.parse(r.body).cookies[0].value.slice(7),'base64url')).user.email==='target@example.com'?status(503,'STORAGE_DEGRADED'):null}),a=e.remote(),before=e.jar;await e.connect();await assert.rejects(e.api.switchTo0(e.api.toUI(a)));assert.equal(e.jar[0].value,before[0].value);assert.notEqual(e.ctx.__navigated,true);});
test('passive sync never recreates a server-deleted or unknown account',async()=>{const e=env();await e.connect();assert.equal(await e.api.syncCurrent(),null);assert.equal(e.api.getCurrent(),'current@example.com');assert.equal(e.server.records.size,0);assert.equal(e.server.calls.filter(r=>r.method==='POST'&&r.url.endsWith('/accounts')).length,0);});
test('passive first observation does not overwrite another device session',async()=>{const e=env(),a=e.remote('current@example.com','other-device');await e.connect();await assert.rejects(e.api.syncCurrent(),x=>x.code==='SESSION_CONFLICT');assert.equal(e.server.records.get(a.id).credentialRevision,1);assert.equal(e.server.calls.filter(r=>r.method==='PUT'&&r.url.endsWith('/credentials')).length,0);});
test('explicit current-session save creates remote record and does not persist local account arrays',async()=>{const e=env();await e.connect();const a=await e.api.syncCurrent({allowCreate:true,force:true});assert.equal(a.email,'current@example.com');assert.equal(e.server.records.size,1);assert.equal(e.server.credentials.size,1);assert.ok(e.gmWrites.every(([k])=>k==='arena.vault.connection.v1'));});
test('repeated unchanged credential observation avoids lease writes',async()=>{const e=env();e.remote('current@example.com','session');await e.connect();await e.api.syncCurrent();const before=e.server.calls.length;await e.api.syncCurrent();assert.equal(e.server.calls.slice(before).filter(r=>r.method!=='GET').length,0);});
test('cross-tab browser lock denial does not change Cookie',async()=>{const e=env({lockBusy:true}),a=e.remote(),before=e.jar;await e.connect();assert.equal(await e.api.switchTo(e.api.toUI(a)),false);assert.deepEqual(e.jar,before);assert.equal(e.trace.includes('cookie.delete'),false);});
test('persistent Cookie keeps actual expiration instead of adding 400 days',async()=>{const e=env();const value={...cookie(),session:false,expirationDate:Math.floor(Date.now()/1000)+2000};await e.api.setCookie(value);assert.equal(e.jar[0].expirationDate,value.expirationDate);});
test('session Cookie stays session-only',async()=>{const e=env();await e.api.setCookie(cookie());assert.equal(e.jar[0].expirationDate,undefined);});
test('unchecked remember explicitly deletes existing server password after login',async()=>{const e=env(),a=e.remote();e.server.records.get(a.id).hasPassword=true;e.server.records.get(a.id).passwordRevision=1;e.server.passwords.set(a.id,'old');await e.connect();const r=await e.api.signInEmail(a.email,'new',{remember:false});assert.ok(r.rec);assert.equal(e.server.passwords.has(a.id),false);assert.equal(e.server.calls.find(r=>r.method==='DELETE'&&r.url.endsWith('/password')).headers['If-Match'],'"r1"');});
test('failed login from logged-out state clears newly set Cookie during rollback',async()=>{const e=env({cookies:[],loginOk:false});await e.connect();const r=await e.api.signInEmail('target@example.com','bad',{remember:false});assert.ok(r.error);assert.equal(e.jar.length,0);});
test('migration failure retains all legacy stores and does not expose password in config',async()=>{const e=env({confirm:[true,true],intercept:r=>r.method==='PUT'&&r.url.endsWith('/credentials')?status(503,'STORAGE_UNAVAILABLE'):null});e.gm.set('accounts.v2',[{email:'old@example.com',cookies:[cookie('old@example.com')],pw:'old-secret'}]);await e.connect();await e.api.migrateLegacy();assert.equal(e.gm.has('accounts.v2'),true);assert.equal(e.gmDeleted.includes('accounts.v2'),false);assert.ok(!JSON.stringify(e.gm.get('arena.vault.connection.v1')).includes('old-secret'));});
test('migration cleanup only happens after remote Cookie and password verification',async()=>{const e=env({confirm:[true,true,true]});e.gm.set('accounts.v2',[{email:'old@example.com',cookies:[cookie('old@example.com')],pw:'old-secret',quota:{credits:0,creditsAt:Date.now()}}]);await e.connect();await e.api.migrateLegacy();assert.equal(e.gm.has('accounts.v2'),false);assert.equal(e.server.records.size,1);assert.ok(e.server.calls.some(r=>r.url.endsWith('/credentials/read')));assert.ok(e.server.calls.some(r=>r.url.endsWith('/password/read')));assert.equal([...e.server.records.values()][0].quota.credits,0);});
test('duplicate migration never overwrites existing server record and retains legacy',async()=>{const e=env({confirm:[true,true]}),a=e.remote('old@example.com');e.gm.set('accounts.v2',[{email:'old@example.com',cookies:[cookie('old@example.com','legacy')]}]);await e.connect();await e.api.migrateLegacy();assert.equal(e.server.records.get(a.id).credentialRevision,1);assert.equal(e.gm.has('accounts.v2'),true);});
test('declining password upload retains old store instead of silently losing password',async()=>{const e=env({confirm:[true,false]});e.gm.set('accounts.v2',[{email:'old@example.com',cookies:[cookie('old@example.com')],pw:'private'}]);await e.connect();await e.api.migrateLegacy();assert.equal(e.gm.has('accounts.v2'),true);assert.equal(e.server.passwords.size,0);});
test('time adapter converts JS milliseconds to Unix seconds and retains zero',()=>{const e=env();const q=e.api.quotaToServer({credits:0,creditsAt:1700000000000,blockedUntil:1700000001000,blockedAt:1700000000000});assert.equal(q.creditsAt,1700000000);assert.equal(q.credits,0);assert.equal(q.blockedUntil,1700000001);assert.equal(e.api.quotaFromServer(q).creditsAt,1700000000000);});
test('legacy mirror adapter converts actual companion cache shape',()=>{const e=env();const q=e.api.legacyQuota({mirror:{'amp.lite.v2.usd':JSON.stringify({balanceRemainingUsd:0,allowanceUsd:10,at:1700000000000})}});assert.equal(q.usd,0);assert.equal(q.allowance,10);assert.equal(q.usdAt,1700000000000);});
test('transport requires supported manager and explicitly blocks redirects and ambient cookies',async()=>{const e=env();let seen;e.ctx.GM_xmlhttpRequest=o=>{seen=o;o.onload({status:200,responseText:'{}',responseHeaders:'',finalUrl:o.url})};await e.api.gmTransport({url:'https://meamoe.top/koa/arena-vault/v1/connection',method:'GET',headers:{}});assert.equal(seen.redirect,'error');assert.equal(seen.anonymous,true);assert.equal(seen.fetch,true);e.ctx.GM_info.version='5.3';await assert.rejects(e.api.gmTransport({}),x=>x.code==='UNSUPPORTED_MANAGER');});

test('declining preservation of an unknown current account cancels switch without touching Cookie',async()=>{const e=env({confirm:[false]}),a=e.remote(),before=e.jar;await e.connect();assert.equal(await e.api.switchTo0(e.api.toUI(a)),false);assert.deepEqual(e.jar,before);assert.equal(e.trace.includes('cookie.delete'),false);});

test('connection key entry never uses a page-DOM input field',()=>{assert.match(source,/@sandbox\s+DOM/);assert.doesNotMatch(source,/unsafeWindow/);const section=source.slice(source.indexOf('  async function openConnection()'),source.indexOf('  async function editPassword('));assert.match(section,/prompt\('粘贴私有连接链接/);assert.doesNotMatch(section,/el\('input'/);assert.doesNotMatch(section,/input\.value/);});
