const test=require('node:test'),assert=require('node:assert/strict');
const path=require('node:path');
const {createArenaVaultClient}=require(require('node:fs').existsSync(path.join(__dirname,'../assets/account-vault-client.js'))?'../assets/account-vault-client.js':'./account-vault-client.js');
const {fixture,cookie,bundle,clone,webcrypto}=require('./account-vault-fixture.cjs');
global.crypto=webcrypto;
const link='https://meamoe.top/koa/arena-vault/connect#key='+'A'.repeat(43);
function client(server=fixture(),extra={}){const writes=[],timers=[];let saved=null;const v=createArenaVaultClient({send:server.send,persist:x=>{saved=x;writes.push(clone(x))},readConfig:()=>saved,clearConfig:()=>{saved=null},schedule:fn=>{timers.push(fn);return timers.length},unschedule:()=>{},...extra});return{v,server,writes,timers};}
async function connected(){const c=client();await c.v.connect(link);return c;}
test('connection URL rejects wrong origin/path/query/duplicate key and credentials',()=>{const{v}=client();for(const u of [link.replace('https:','http:'),link.replace('meamoe.top','evil.test'),link.replace('/koa/','/'),link.replace('/connect#','/connect?key=x#'),link+'&key='+'B'.repeat(43),link+'&x=1',link.replace('meamoe.top','user:pass@meamoe.top')])assert.throws(()=>v.parseLink(u));assert.equal(v.parseLink(link),'A'.repeat(43));});
test('only verified connection configuration is persisted; no account arrays',async()=>{const{v,server,writes}=await connected();server.add('a@b.c');await v.refresh();assert.equal(writes.length,1);assert.deepEqual(Object.keys(writes[0]).sort(),['key','vaultId']);assert.ok(server.calls.every(x=>x.url.startsWith(v.BASE+'/v1/')&&!x.url.includes(server.key)));});
test('invalid key never persists or replaces remote data',async()=>{const c=client();await assert.rejects(c.v.connect(link.replace(/A/g,'B')),e=>e.status===401);assert.equal(c.writes.length,0);assert.equal(c.v.ready(),false);});
test('restore does not rewrite config and trigger cross-tab listener loops',async()=>{const c=await connected();await c.v.restore();assert.equal(c.writes.length,1);});
test('failed connection snapshot does not persist key',async()=>{const server=fixture();const c=client(server,{send:async r=>r.url.endsWith('/settings')?{status:503,body:{code:503,data:{errorCode:'VAULT_UNAVAILABLE'}}}:server.send(r)});await assert.rejects(c.v.connect(link));assert.equal(c.writes.length,0);});
test('metadata projection never caches Cookie/password fields returned by server',async()=>{const c=await connected();c.server.add('a@b.c',{cookies:[cookie()],password:'secret',pw:'secret',credentials:{ciphertext:'secret'}});await c.v.refresh();const a=c.v.accounts()[0];for(const k of ['cookies','password','pw','credentials'])assert.equal(a[k],undefined);});
test('mutations use stable idempotency key on ambiguous network retry',async()=>{const c=await connected();c.server.drop=r=>r.method==='POST'&&r.url.endsWith('/accounts');const a=await c.v.create({email:'a@b.c'});assert.ok(a.id);assert.equal(c.server.records.size,1);const req=c.server.calls.filter(r=>r.method==='POST'&&r.url.endsWith('/accounts'));assert.equal(req.length,2);assert.equal(req[0].headers['Idempotency-Key'],req[1].headers['Idempotency-Key']);});
test('CAS conflict is not silently retried using a newer revision',async()=>{const c=await connected();const a=await c.v.create({email:'a@b.c'});c.server.records.get(a.id).revision++;await assert.rejects(c.v.patch(a,{name:'unsafe'}),e=>e.status===412);assert.equal(c.server.calls.filter(r=>r.method==='PATCH').length,1);assert.notEqual(c.server.records.get(a.id).name,'unsafe');});
test('credentials are fetched only inside a lease and not stored in metadata',async()=>{const c=await connected();let a=await c.v.create({email:'a@b.c'});await c.v.withLease(a,async l=>{await l.write(0,bundle([cookie('a@b.c')]));const r=await l.read();assert.equal(r.bundle.cookies.length,1);});assert.equal(c.server.leases.size,0);assert.equal(c.v.find(a.id).cookies,undefined);const req=c.server.calls.find(r=>r.method==='PUT'&&r.url.endsWith('/credentials'));assert.equal(req.headers['If-Match'],'"r0"');assert.ok(req.headers['X-Lease-Token']);});
test('lease release runs even when operation fails',async()=>{const c=await connected(),a=await c.v.create({email:'a@b.c'});await assert.rejects(c.v.withLease(a,async()=>{throw new Error('operation failed')}));assert.equal(c.server.leases.size,0);});
test('lease renewal failure prevents subsequent secret writes',async()=>{const s=fixture();const c=client(s,{send:async r=>r.url.endsWith('/renew')?{status:409,body:{code:409,data:{errorCode:'LEASE_MISMATCH'}}}:s.send(r)});await c.v.connect(link);const a=await c.v.create({email:'a@b.c'});await c.v.withLease(a,async l=>{c.timers[0]();await new Promise(r=>setImmediate(r));assert.throws(l.guard);await assert.rejects(l.write(0,bundle([cookie()])));});assert.equal(c.server.calls.filter(r=>r.method==='PUT'&&r.url.endsWith('/credentials')).length,0);});
test('password is fetched on demand and explicit delete persists independently',async()=>{const c=await connected();let a=await c.v.create({email:'a@b.c'});a=await c.v.password(a,'private-password');await c.v.refresh();assert.equal(c.server.calls.filter(r=>r.url.endsWith('/password/read')).length,0);assert.equal(await c.v.readPassword(a),'private-password');await c.v.password(a,null);assert.equal(c.v.find(a.id).hasPassword,false);assert.equal(c.v.find(a.id).password,undefined);});
test('zero quota and normalized mirror survive round trip',async()=>{const c=await connected();let a=await c.v.create({email:'a@b.c'});a=await c.v.quota(a,{credits:0,creditsAt:10});a=await c.v.putMirror(a,{'amp.lite.v2.balance':{credits:0,creditsAt:10}});assert.equal(c.v.find(a.id).quota.credits,0);assert.equal((await c.v.readMirror(a))['amp.lite.v2.balance'].credits,0);});
test('server-side delete removes only chosen account',async()=>{const c=await connected();const a=await c.v.create({email:'a@b.c'});await c.v.create({email:'x@y.z'});await c.v.remove(a);assert.equal(c.v.accounts().length,1);assert.equal(c.v.accounts()[0].email,'x@y.z');});
test('expired changes cursor re-fetches authoritative snapshot',async()=>{const c=await connected();c.server.add('new@b.c');c.server.reset();await c.v.poll();assert.equal(c.v.accounts()[0].email,'new@b.c');});
test('401 clears loaded metadata and disables connection',async()=>{const c=await connected();await c.v.create({email:'a@b.c'});c.server.key='B'.repeat(43);await assert.rejects(c.v.refresh(),e=>e.status===401);assert.equal(c.v.ready(),false);assert.equal(c.v.accounts().length,0);});
test('late response from old connection cannot repopulate metadata',async()=>{const c=await connected();await c.v.create({email:'a@b.c'});let release;c.server.block=r=>r.url.endsWith('/accounts')?new Promise(r=>{release=r}):undefined;const pending=c.v.refresh();await new Promise(r=>setImmediate(r));await c.v.disconnect();release();await assert.rejects(pending,e=>e.code==='CONNECTION_CHANGED');assert.equal(c.v.accounts().length,0);});
test('hotkeys persist through settings and tags, preserving unrelated tags',async()=>{const c=await connected();const a=await c.v.create({email:'a@b.c',tags:['work']});await c.v.saveHotkeys({panel:'F2',accounts:{'a@b.c':'Alt+KeyA'}});assert.equal(c.v.hotkeys().panel,'F2');assert.deepEqual(c.v.find(a.id).tags,['work','amp-hotkey:Alt+KeyA']);assert.equal(c.writes.length,1);});
test('client double-checks hostile cookie bundles before Cookie API access',()=>{const{v}=client();for(const patch of [{domain:'evil.test'},{path:'/other'},{secure:false},{name:'unrelated'},{value:'x; cookie=injected'}])assert.throws(()=>v.validateBundle(bundle([{...cookie(),...patch}])));assert.throws(()=>v.validateBundle(bundle([cookie(),cookie()])));assert.throws(()=>v.validateBundle(bundle([{...cookie(),name:'arena-auth-prod-v1.1'}])));assert.throws(()=>v.validateBundle(bundle([cookie(),{...cookie(),name:'arena-auth-prod-v1.0'}])));});
test('bundle byte-size limit is UTF-8, not JavaScript character count',()=>{const{v}=client();assert.throws(()=>v.validateBundle(bundle([{...cookie(),value:'界'.repeat(22000)}])));});
test('final URL mismatch fails closed; token is only sent to fixed API base',async()=>{const s=fixture(),c=client(s,{send:async r=>({...await s.send(r),finalUrl:'https://other.invalid/'})});await assert.rejects(c.v.connect(link),e=>e.code==='REDIRECT_BLOCKED');assert.equal(c.writes.length,0);});
